services:
  - type: web
    name: vpp-report
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python pdf_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
